### ISSUE TITLE
Error when try connect a network

### ISSUE THREAD

**Issue by destebanweb** [pocmo/Yaaic#242]
Hi,

When I try to connect to a server this error appears and I have no idea how to fix it.

When for example I touch the connect button using the menu, the client appears on the server as entering correctly but when I try to access the conversation activity, the application crashes with the following error.

I have activated the FOREGROUND SERVICE but the application still does not work.

android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=-2 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 category=progress vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1737)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by pocmo** [comment]
I haven't updated Yaaic in a long while. This exception looks like it needs support for the new notification channels that were added in one of the last Android versions. The last time I wrote some code for Yaaic those didn't exist. :)
